name = "glemtext"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "A small library for parsing Gemini's gemtext"
licences = ["MPL-2.0"]
repository = { type = "github", user = "username", repo = "project" }

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/. 

[dependencies]
gleam_stdlib = "~> 0.35 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
